<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidateCreditCard"
     targetNamespace="http://xmlns.oracle.com/CCValidate/CCValidate/ValidateCreditCard"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://xmlns.oracle.com/CCValidate/CCValidate/ValidateCreditCard"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="validateCC_ptt_PLT">
        <plnk:role name="validateCC_ptt_Role" portType="ns1:validateCC_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/CCValidate/CCValidate/ValidateCreditCard" location="http://localhost:7101/soa-infra/services/default/CCValidate!1.0/WSDLs/ValidateCreditCard.wsdl"/>
</wsdl:definitions>
