<wsdl:definitions
     name="CreditCardDBService"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CCValidate/CCValidate/CreditCardDBService"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CCValidate/CCValidate/CreditCardDBService"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreditCardDBService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CreditCardDBService_plt" >
    <plt:role name="CreditCardDBService_role" >
      <plt:portType name="tns:CreditCardDBService_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreditCardDBService" schemaLocation="../Schemas/CreditCardDBService_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CreditCardDBServiceSelect_inputParameters">
        <wsdl:part name="CreditCardDBServiceSelect_inputParameters" element="top:CreditCardDBServiceSelect_ccNumInputParameters"/>
    </wsdl:message>
    <wsdl:message name="BcaCreditcardsCollection_msg">
        <wsdl:part name="BcaCreditcardsCollection" element="top:BcaCreditcardsCollection"/>
    </wsdl:message>
    <wsdl:portType name="CreditCardDBService_ptt">
        <wsdl:operation name="CreditCardDBServiceSelect">
            <wsdl:input message="tns:CreditCardDBServiceSelect_inputParameters"/>
            <wsdl:output message="tns:BcaCreditcardsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
