<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ReceiveData"
     targetNamespace="http://oracle.com/sca/soapservice/Basics/HelloWorld/ReceiveData"
     xmlns:tns="http://oracle.com/sca/soapservice/Basics/HelloWorld/ReceiveData"
     xmlns:inp1="http://www.example.org/ns/porder"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org/ns/porder" schemaLocation="../Schemas/po.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" type="inp1:PurchaseOrderType"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
