<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="Booking"
     targetNamespace="http://xmlns.oracle.com/Projects/BookingSystem/Booking"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/Projects/BookingSystem/Booking"
     xmlns:ns1="http://www.example.org/ns/enroll"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://localhost:7101/soa-infra/services/default/BookingSystem!1.0/Booking.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="Booking">
        <plnk:role name="BookingProvider" portType="client:Booking"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.example.org/ns/enroll" schemaLocation="../Schemas/enrollment_2.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="BookingRequestMessage">
        <wsdl:part name="payload" element="ns1:enrollmentRequest"/>
    </wsdl:message>
    <wsdl:message name="BookingResponseMessage">
        <wsdl:part name="payload" element="ns1:enrollmentResponse"/>
    </wsdl:message>
    <wsdl:message name="BookingFaultMessage">
        <wsdl:part name="payload" element="ns1:enrollmentFault"/>
    </wsdl:message>
    <wsdl:portType name="Booking">
        <wsdl:operation name="process">
            <wsdl:input message="client:BookingRequestMessage"/>
            <wsdl:output message="client:BookingResponseMessage"/>
            <wsdl:fault name="paymentFault" message="client:BookingFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BookingBinding" type="client:Booking">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="paymentFault">
                <soap:fault name="paymentFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="booking_client_ep">
        <wsdl:port name="Booking_pt" binding="client:BookingBinding">
            <soap:address location="http://localhost:7101/soa-infra/services/default/BookingSystem!1.0*soa_ccad2b3d-6881-462d-a980-5dd817848dfa/booking_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
