<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://www.example.org/ns/fulfillment" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/JMSProducer/JMSConsumer/jmsConsumer"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://www.example.org/ns/intorder"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/JMSProducer/JMSConsumer/fileWriter">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/jmsConsumer.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ShippingRequest" namespace="http://www.example.org/ns/fulfillment"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/fileWriter.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ShippingRequest" namespace="http://www.example.org/ns/fulfillment"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 09 12:18:17 CET 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:ShippingRequest>
      <ns0:orderId>
        <xsl:value-of select="/ns0:ShippingRequest/ns0:orderId"/>
      </ns0:orderId>
      <ns0:custName>
        <xsl:value-of select="/ns0:ShippingRequest/ns0:custName"/>
      </ns0:custName>
      <ns0:shippingAddress>
        <ns0:street>
          <xsl:value-of select="/ns0:ShippingRequest/ns0:shippingAddress/ns0:street"/>
        </ns0:street>
        <ns0:city>
          <xsl:value-of select="/ns0:ShippingRequest/ns0:shippingAddress/ns0:city"/>
        </ns0:city>
        <ns0:state>
          <xsl:value-of select="/ns0:ShippingRequest/ns0:shippingAddress/ns0:state"/>
        </ns0:state>
        <ns0:zip>
          <xsl:value-of select="/ns0:ShippingRequest/ns0:shippingAddress/ns0:zip"/>
        </ns0:zip>
        <ns0:country>
          <xsl:value-of select="/ns0:ShippingRequest/ns0:shippingAddress/ns0:country"/>
        </ns0:country>
      </ns0:shippingAddress>
    </ns0:ShippingRequest>
  </xsl:template>
</xsl:stylesheet>
