<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:nsd0="http://www.example.org/ns/porder"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl nsd0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Basics/HelloWorld/WriteData"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ReceiveData.wsdl"/>
        <oracle-xsl-mapper:rootElement name="part1" namespace=""/>
        <oracle-xsl-mapper:rootElementDatatype name="PurchaseOrderType" namespace="http://www.example.org/ns/porder"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/WriteData.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://www.example.org/ns/porder"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 08 10:57:32 CET 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <nsd0:PurchaseOrder>
      <nsd0:custID>
        <xsl:value-of select="/part1/nsd0:custID"/>
      </nsd0:custID>
      <nsd0:ID>
        <xsl:value-of select="/part1/nsd0:ID"/>
      </nsd0:ID>
      <nsd0:payOption>
        <xsl:value-of select="/part1/nsd0:payOption"/>
      </nsd0:payOption>
      <nsd0:shipChoice>
        <xsl:value-of select="/part1/nsd0:shipChoice"/>
      </nsd0:shipChoice>
      <nsd0:status>
        <xsl:value-of select="/part1/nsd0:status"/>
      </nsd0:status>
      <nsd0:ccType>
        <xsl:value-of select="/part1/nsd0:ccType"/>
      </nsd0:ccType>
      <nsd0:ccNumber>
        <xsl:value-of select="/part1/nsd0:ccNumber"/>
      </nsd0:ccNumber>
      <nsd0:items>
        <xsl:for-each select="/part1/nsd0:items/nsd0:item">
          <nsd0:item>
            <nsd0:productId>
              <xsl:value-of select="nsd0:productId"/>
            </nsd0:productId>
            <nsd0:productName>
              <xsl:value-of select="nsd0:productName"/>
            </nsd0:productName>
            <nsd0:price>
              <xsl:value-of select="nsd0:price"/>
            </nsd0:price>
            <nsd0:quantity>
              <xsl:value-of select="nsd0:quantity"/>
            </nsd0:quantity>
          </nsd0:item>
        </xsl:for-each>
      </nsd0:items>
    </nsd0:PurchaseOrder>
  </xsl:template>
</xsl:stylesheet>
